### ISSUE TITLE
Typo in "parseTempalte"

### ISSUE THREAD

**Issue by laurent22** [joplin/plugin-templates#1]
Just had a look at the code and it looked good overall. I've just noticed a typo in "parseTempalte" => "parseTemplate", and since you use this function a lot it would be better to fix it now:

https://github.com/joplin/plugin-templates/blob/1eeed0e69beba172b85a190499c7e0246bdbc2be/src/parser.ts#L1

**Comment by nishantwrp** [comment]
Fixed by 4efaa84e0d7adc7dbd1a7a7eab2c3ea3fe638246
