### ISSUE TITLE
Note "disappears" if created from template and no title added

### ISSUE THREAD

**Issue by amandamcg** [joplin/plugin-templates#17]
Repro: 
- Tools > Create New Todo [or Note] from template > Choose template from dropdown
- Note appears, as expected, but doesnt have a title
- Clicking another note will delete the template note 

This only happens if you create a note and don't edit it at all. Because you can "fill out" a note using template variables, this seems like a reasonable use case to support. 

Ideally the normal case of the first line of the template becoming the title would work (and something like https://github.com/joplin/plugin-templates/issues/16 would make that more customizable)

**Comment by laurent22** [comment]
When new notes are created they are initially in provisional state, which means they are deleted if they are not modified. However in this case I guess it shouldn't happen since the note contains the template text, so maybe it's actually a bug in the main app.

**Comment by laurent22** [comment]
@nishantwrp, since you removed the bug label, can you confirm that it's indeed not a bug and just how you've implemented it? Or is it something else?

**Comment by nishantwrp** [comment]
Actually I've just used the newNote command to create a new note with template. So, maybe it's the way main app handles it?

**Comment by laurent22** [comment]
Yes I see it now, it creates the note as provisional even when a body is set. This is normal actually if the body is static, but in your case since you create the note body based on user input it shouldn't do that. What do you want to do about it?

**Comment by nishantwrp** [comment]
> but in your case since you create the note body based on user input it shouldn't do that

Do you mean that this shouldn't happen in the case when there are custom template variables in the template? Or it shouldn't happen in general for all notes created with the help of templates

**Comment by laurent22** [comment]
What's your opinion? What do you think would be better?

**Comment by nishantwrp** [comment]
I think to make the UX simple and intuitive we can fix it in the case of all notes created with a template irrespective of if it had any template variables or not. Thoughts?

**Comment by laurent22** [comment]
Yes that makes sense, and that way all templates are handled in a consistent way. What do you want to do next then?

**Comment by nishantwrp** [comment]
If instead of using the newNote command. I use the data api to create a new note / todo. It won't mark the note as provisional, right?

**Comment by laurent22** [comment]
Indeed it won't mark it as provisional.

**Comment by nishantwrp** [comment]
Okay, then. I'll refactor the code to fix this behaviour.
