### ISSUE TITLE
Additional Keyboard shortcuts (enhancement)

### ISSUE THREAD

**Issue by amandamcg** [joplin/plugin-templates#18]
Would be nice to be able to assign a keyboard shortcut for "create to-do from template" and "create note from template".

**Comment by nishantwrp** [comment]
Sure, we can do that. Can you suggest what could be the shortcuts for these actions? 

Here are the already existing shortcuts.
https://github.com/joplin/plugin-templates/blob/1737b92fb9458629914b65d35058f4f3c2350335/src/index.ts#L158-L196

**Comment by JackGruber** [comment]
I think there was a bug in Joplin, that not all possible commands would be shown in the Keyboard shortcuts ... 
Have there once with another plugin something read. If you enter the command manually into the `keymap-desktop.json`, it works.

**Comment by amandamcg** [comment]
I would make them Alt+Ctrl+Shift+N and Alt+Ctrl+Shift+T. I realize those are very long, but that keeps them with the same pattern as your Default Template ones which makes it easier to remember.
