### ISSUE TITLE
Upgrade Joplin to 2.2.5+ then restart to use this plugin

### ISSUE THREAD

**Issue by kimcosmos** [joplin/plugin-templates#21]
Is it just me?
Manjaro, Appimage
Joplin 2.1.9 (prod, linux)

Client ID: 6edc801e81444a1185b31bde82d25ab6
Sync Version: 2
Profile Version: 39
Keychain Supported: No

Revision: 882d663

**Comment by nishantwrp** [comment]
Actually, this is not a bug. You need version `>=2.2.5` to use this plugin. That's just a pre-release right now. So, you'll need to do the following 

- Go to `Settings` > `Application`
- Enable `Get pre-releases when checking for updates`
- Check for updates again
- Update to the latest pre-release
- Install templates plugin

**Comment by kimcosmos** [comment]
ok thanks

**Comment by roman-r-m** [comment]
I think the actual minimum version is 1.8.x -- that's when the API change has been first introduced.

**Comment by nishantwrp** [comment]
@roman-r-m I manually changed the min version to ensure both the legacy feature and this plugin don't run together.

**Comment by kimcosmos** [comment]
Now its getting wierd. I upgraded and was able to install the plugin but it is greyed out and asking me to upgrade again.
Appimage again from https://github.com/laurent22/joplin/releases/tag/v2.2.6
Joplin 2.1.9 (prod, linux)
Client ID: 6edc801e81444a1185b31bde82d25ab6
Sync Version: 2
Profile Version: 39
Keychain Supported: No

Revision: 882d663

**Comment by nishantwrp** [comment]
It's showing you still have `Joplin 2.1.9 (prod, linux)`?

**Comment by kimcosmos** [comment]
oops yeah. I  will completely uninstall and reinstall again. Sorry. It started with the message about templates being replaced with this version. I was sure it said it was a later version but the pasting does not lie
