### ISSUE TITLE
Input field is cut off

### ISSUE THREAD

**Issue by JackGruber** [joplin/plugin-templates#28]
The text input field is displayed truncated
![grafik](https://user-images.githubusercontent.com/24863925/129445119-ebd79e39-21f2-4941-94eb-4a3c84d3033d.png)

```
---
Gemeldet: enum(eMail, Telefon, Besichtigung)
Gemeldet an: text

---

```

**Comment by nishantwrp** [comment]
I've released a new version i.e. `1.1.3`. It should be fixed when you update the plugin.
