### ISSUE TITLE
Space and special characters in variable name leads to error

### ISSUE THREAD

**Issue by JackGruber** [joplin/plugin-templates#29]
Spaces, German umlauts, special characters, leading numbers lead to errors in variable names.
![grafik](https://user-images.githubusercontent.com/24863925/129445508-5aabc26f-c522-4a65-a688-9d7b46125aa5.png)

Possibly check the variable names before parsing if only permitted characters (`a-zA-Z0-9`) are included? 

```
---
Änderung: enum(Einplanen, Ausplanen)
1nderung: text
Aenderung&Test: text

---
```

**Comment by nishantwrp** [comment]
Hmm, yeah we can display a better error message in case of invalid variable names.

**Comment by laurent22** [comment]
> Hmm, yeah we can display a better error message in case of invalid variable names.

If the bug cannot be fixed, indeed the error message should be improved, but the first step would be to understand why it happens. Is it in your code? is it in a library? Why does it happen? Can it be prevented?

You need to investigate a bit the bug before settling down on a better error message. It would be even better if there was no error at all.

**Comment by JackGruber** [comment]
Hm you are right numbers and umlaute (äöüß) are OK 🤦‍♂️ 
I don't know what I tried, but I think I had another error in the template

But for @,# and space I get error messages

**Space**
![grafik](https://user-images.githubusercontent.com/24863925/129452288-7da86deb-e8db-4237-96af-f72c1ac57869.png)
```
---
a enderung: text

---

aenderung: {{a enderung}}
```
**@ char**

![grafik](https://user-images.githubusercontent.com/24863925/129452270-9b20ca9f-00cf-4c13-86d1-f3e5f83cef78.png)
```
---
a@enderung: text

---


aenderung: {{a@enderung}}
```

**, char**
![grafik](https://user-images.githubusercontent.com/24863925/129452355-bf731b37-d77f-4a88-8ae0-b88726a81d1c.png)
```
---
a,enderung: text

---

aenderung: {{a,enderung}}
```

**# char**
![grafik](https://user-images.githubusercontent.com/24863925/129452592-5f597652-0f1e-4cc3-a7d4-51f2f6728f86.png)


```
---
a#enderung: text

---


aenderung: {{a#enderung}}
```

**Comment by nishantwrp** [comment]
Yup, I see. These are the errors on the handlebars side. I'll make the error more clear if the variable name itself can't be used in handlebars.
