### ISSUE TITLE
top line does not become title

### ISSUE THREAD

**Issue by Mortimersnodgrass** [joplin/plugin-templates#33]
When I make a new todo and insert a todo from the default template ctrl-alt-i  I'm prompted for the name and the date is appended via my variables. The template is then inserted. The top line of the inserted template (name and date), becomes the title. I think this is supposed to be the default behavior. Untitled notes take the top line as the title.

When I insert a todo template (ctrl-alt-shift-t) it does not take the top line as the title. The title remains untitled.

I'm thinking that it should also grab the top line and make it the title

**Comment by nishantwrp** [comment]
Actually, we are working on a better customizable way to define your note `title` or `tags`. Please see [this](https://discourse.joplinapp.org/t/specifying-note-title-and-tags-in-templates/19380) topic on the forum.

**Comment by CalebJohn** [comment]
@nishantwrp do you know why the too line is used as the title for regular notes, but not Todos?

**Comment by nishantwrp** [comment]
I think @Mortimersnodgrass means that when he creates a new note manually and does insertText using template. But it doesn't in case when a note is created directly with newNoteUsingTemplate.

**Comment by CalebJohn** [comment]
> I think @Mortimersnodgrass means that when he creates a new note manually and does insertText using template the title automatically becomes the first line. But it doesn't in case when a note is created directly with newNoteUsingTemplate.

Thanks, i didn't understand that. I'm with you now.

**Comment by Mortimersnodgrass** [comment]
> Actually, we are working on a better customizable way to define your note `title` or `tags`. Please see [this](https://discourse.joplinapp.org/t/specifying-note-title-and-tags-in-templates/19380) topic on the forum.

The way the insert todo template works is perfect. I just wanted the same for the create new template.

My  use case is that about 15-20 times a month I need to create a todo with a set of 6 action items. The title must be the client name and date. With the insert todo template I just click on the appropriate folder, then create a todo, then insert the template which prompts for the client name and fills in the date. Since the top line becomes the title, all I need to do is enter the client name, which changes every time and the todo is created along with the title. This is wonderful.

With the create a todo template, it is actually harder because I need to copy and paste from the top line into the title.

I can see the other ideas with tags and a title field, but for me, perfection is simply using the top line as the title which is the default behavior for new notes or todos

**Comment by nishantwrp** [comment]
Yup, I get your use case and point. But currently a lot of users want to customize the title and therefore making the top line and title automatically doesn't seem a good idea to me.

Taking about the current state of the discussion, we are planning to introduce special variables for title and use the template title as the fallback. So, you'll be able to achieve what you want after that's implemented.

**Comment by Mortimersnodgrass** [comment]
> Yup, I get your use case and point. But currently a lot of users want to customize the title and therefore making the top line and title automatically doesn't seem a good idea to me.
> 
> Taking about the current state of the discussion, we are planning to introduce special variables for title and use the template title as the fallback. So, you'll be able to achieve what you want after that's implemented.

I just wanted to thank you for the fabulous plugin and all the work done. I thought that the new todo from template should be consistent with manual todos and notes. If there is good reasons not to be consistent, I get that. Either way, it is making my work easier and being a help for me, so thank you very much.

I'll continue to track things and see if I can gain even more benefit.
