### ISSUE TITLE
template_title & template_tags is not working

### ISSUE THREAD

**Issue by LevonLu** [joplin/plugin-templates#38]
I try to use the example in [README.MD](https://github.com/joplin/plugin-templates#readme) to test templatetitle, it's not work.
I copy the example in my Joplin by Typora. This is the sourcecode-mode in Typora view.
![image](https://user-images.githubusercontent.com/59905431/130790510-8ec980d3-b566-4c83-8508-6b40b6563bbe.png)
this error was appear when I created note from this template.
![image](https://user-images.githubusercontent.com/59905431/130789959-6d4bcb78-c2f8-4c62-b629-23780ee448e6.png)

**Comment by nishantwrp** [comment]
Actually it will be released in a newer version of the plugin.
