### ISSUE TITLE
FR: Add an example for custom date time

### ISSUE THREAD

**Issue by gerroon** [joplin/plugin-templates#41]
Hi

Is it possible to add an example that shows how to use the custom_date ({{#custom_datetime}})  formatting? 

thanks

**Comment by tessus** [comment]
Here's an example:

```
---
template_title: Week {{#custom_datetime}}WW{{/custom_datetime}} - {{bowm}}

---
Text of note here

```

**Comment by gerroon** [comment]
Hi
Thanks for the example but I meant the formatting of the custom date. Right now it goes with the Joplin's date format but none of the Joplin's options are how I need. I want something like `mmmm-ddd-yyyy`

**Comment by tessus** [comment]
As the README states, it is using moment,js. The format is pretty obvious and described here: https://momentjs.com/docs/#/displaying/format/

>  I want something like mmmm-ddd-yyyy

you have to be more specific. what is mmmm supposed to mean? The month as string? e.g. August? What about ddd? Depending on the system, these things can mean X different things.

**Comment by gerroon** [comment]
Hi

I looked at the momentjs page and I do not understand. It is not so obvious to me how to use this with this plugin. I am not a JS developer and I personally do not know how to integrate it and that is why I asked for a formatted example.

My formatting had typos, I am looking for an example for `month-day-year`

**Comment by tessus** [comment]
> month-day-year

I told you, you had to be more specific.

Above can be:

- 08-28-2021
- 8-28-21
- Aug-28-2021
- August-28th-2021
- and so on (probably 10 more combinations)

Thus you click on the link and look for the format you are looking for.

For month you have the following options:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/223439/131234300-e849f6f9-434a-4307-8ddb-523b6c15668d.png">

So for a format 08-28-2021, it would be: `{{#custom_datetime}}MM-DD-YYYY{{/custom_datetime}}`

**Comment by gerroon** [comment]
Thanks for the detailed reply, now it makes perfect sense to me.
