### ISSUE TITLE
Feature request: enable special variables also when inserting template into note

### ISSUE THREAD

**Issue by butterflyx** [joplin/plugin-templates#48]
I love this plugin and also the Special variables feature for notes creates new from template.
Just missing it when inserting a template with Strg+Alt+i into an existing note. Esp adding the tags would be very helpful in my point of view.

**Comment by JackGruber** [comment]
For this feature a vote is running
https://discourse.joplinapp.org/t/template-plugin/17470/93?u=jackgruber
