### ISSUE TITLE
no template folder, unable to create template on joplin v2.6.10 windows, Templates v2.2.0

### ISSUE THREAD

**Issue by PeeTeeH** [joplin/plugin-templates#54]
Joplin 2.6.10, windows, first time installation of plugin-templates

After Joplin restart there is NO template folder. 
In tools menu there is NO command to show templates folder. 
While trying to create note form template or showing templates, 

![image](https://user-images.githubusercontent.com/37756000/150324195-a53d1fed-e3f8-4b03-9c78-628262745a10.png)
![image](https://user-images.githubusercontent.com/37756000/150324268-1911030e-08f3-47ee-91af-7c6b7416e4ac.png)
![image](https://user-images.githubusercontent.com/37756000/150324324-dbc312b1-4074-4c4e-baef-76dc59f469a2.png)
![image](https://user-images.githubusercontent.com/37756000/150324689-a8a8be02-ce60-4e0b-8ae6-b86091b81250.png)

**Comment by JackGruber** [comment]
Create some notes an add the tag `template` to them. 
https://github.com/joplin/plugin-templates#adding-a-new-template

**Comment by PeeTeeH** [comment]
> Create some notes an add the tag `template` to them. https://github.com/joplin/plugin-templates#adding-a-new-template

it worked!

When I read again the WIKI at https://github.com/joplin/plugin-templates/wiki I noticed it was already described. 
I have read this three times BEFORE posting issue ticked but didn't get it. Sorry!
