### ISSUE TITLE
Missing form data

### ISSUE THREAD

**Issue by CalebJohn** [joplin/plugin-templates#6]
While testing I ran in to an issue a few times while trying to insert a note. The form wasn't being created properly so I was only presented with an empty dialog box. After pressing okay on the box I was given this error in the console.
```
plugin_joplin.plugin.templates.js:273 Error in parsing template. TypeError: Cannot read property 'variables' of undefined
    at t.Parser.<anonymous> (plugin_joplin.plugin.templates.js:273)
    at Generator.next (<anonymous>)
    at i (plugin_joplin.plugin.templates.js:273)
```
I can't reproduce this consistently, but it did happen to me about 4 times during testing. I'll try to get you more information that will help you troubleshoot this. I suspect this might be a bug in the core app, so it could be awhile to find it.

Here is the template that caused it (Not consistently)
```
---
title: text
date: text
hours: number
something: number

---

Date: {{date}}
Title: {{title}}
Hours: {{hours}}
```

**Comment by nishantwrp** [comment]
Can you check if there is any error except the one you mentioned in plugin console or main app console.

**Comment by nishantwrp** [comment]
I just tested this multiple times and never faced this issue. I test on `dev_no_template` branch of the main repo. So, maybe as you said there is a bug in the desktop app itself.

**Comment by CalebJohn** [comment]
> Can you check if there is any error except the one you mentioned in the plugin console or main app console? 

There was no other errors.

There seems to always be a small delay before the form appears, so i wouldn't be surprised if waiting for 10 or more seconds fixes the issue.

**Comment by nishantwrp** [comment]
> so i wouldn't be surprised if waiting for 10 or more seconds fixes the issue.

Can you still check it once, since I can't reproduce this issue.

**Comment by nishantwrp** [comment]
Any updates @CalebJohn?

**Comment by CalebJohn** [comment]
@nishantwrp I have not been able to reproduce this since I reported it. I suspect it's an edge case with the core app that only happens under certain conditions.
Unless you have done something to specifically address this issue I would not assume that it's fixed.

If you want to close this ticket, you need to either:
1. Reproduce and fix the issue (I think this will be too hard)
2. Come up with a reasonable theory of why this happened and why it won't be an issue in the future.
3. Add guards to your code so that if this does happen again you can collect more debug information.

**Comment by nishantwrp** [comment]
According to me it may be happening because of one of the following two reasons

1. A small bug or glitch in the main app.
2. Maybe, it was a little slow and if you waited 5-10 seconds more, the form would've loaded.

Again, these are only some possible reasons i could think of. I was never able to reproduce this issue.

**Comment by CalebJohn** [comment]
Okay, so based on that, what is your plan of action?
