### ISSUE TITLE
Feature Request: Use Notebook Instead of Tag to distinguish templates

### ISSUE THREAD

**Issue by BeatLink** [joplin/plugin-templates#62]
Hey, great plugin! 

My feature request is to have an option in settings to switch between using a template tag or a notebook titled template to distinguish notes that are templates. In the former case, any note given a template tag would be considered a template and in the latter case, any note in a notebook titled Templates would be considered a template. This choice would allow for users to free up their tag lists in their particular usecases

**Comment by miu007** [comment]
vote for it
