### ISSUE TITLE
Remove the support for legacy templates

### ISSUE THREAD

**Issue by nishantwrp** [joplin/plugin-templates#65]
It has been more than 10 months since the plugins first version was released. I think we can safely remove the support for legacy templates now. (https://github.com/joplin/plugin-templates#importing-legacy-templates)

What do you guys think? @laurent22 @CalebJohn

**Comment by laurent22** [comment]
10 months is not that much actually, some people run very old versions, for example when they disable the auto updates. And the day they do update it'd be nice if things work well.

So unless it becomes a burden to maintain this part of the code, I'd suggest keeping it for now.

**Comment by nishantwrp** [comment]
Thanks for the suggestions. Yes it makes sense to support the legacy templates to the point where its not a burden to maintain and doesn't affect the rest of the plugin. Closing the issue.
