### ISSUE TITLE
Must be missing something: templates won't work with custum variables

### ISSUE THREAD

**Issue by Hoffenbar** [joplin/plugin-templates#71]
If I use custum variables, then trying to create a new note from that template, all I get is this:

![image](https://user-images.githubusercontent.com/46227007/209474760-d0339207-927a-4b2b-8c7a-3bac3973171f.png)

And clicking `Ok`, I get this:

![image](https://user-images.githubusercontent.com/46227007/209474778-98eb25e9-7cd5-48ce-8b88-6d5569ac6683.png)

Here is a template I found somewhere in the net as an example:
```
---
name: text
color: dropdown(Red, Yellow, Green)

---

Hi there, {{ name }}. Your favorite color is {{ color }}. This note/to-do was created on {{ datetime }}.
```

Don't know what I'm doing wrong...

Supportinfo:

```
Joplin 2.9.17 (prod, win32)

Client-ID: ef58bde158c94e218c1c2af31a3e3966
Sync-Version: 3
Profil-Version: 41
Unterstützter Schlüsselbund: Nein

Revision: a84a8e7
```

I stored the templates within a notebook named `Templates` within Joplin-DB, not in the file system.

**Comment by nishantwrp** [comment]
I'm unable to reproduce this issue using the template you provided. I'm on the same joplin version `2.9.17`. Can you maybe try restarting joplin?

**Comment by Hoffenbar** [comment]
Yes, I've restartet joplin, without success. Maybe a conflict with some other plugin, of which I have many installed and some of them active.

**Comment by Hoffenbar** [comment]
Very mysterious. After starting the PC today and again starting a new Joplin instance, the example works as expected......

**Comment by Hoffenbar** [comment]
Newly opened Joplin. Now again it does not work. Very strange. Nothing else changed in my system.

**Comment by JackGruber** [comment]
I have noticed since one or two versions in Joplin with my plugins that message boxes are somtimes loaded empty and the content is not displayed. I have not yet been able to debug the error, but I almost assume that it is not the fault of the plugin but of Joplin, as it also happens with older plugins. 

The second error message is probably only due to the message box not loading correctly.

**Comment by JackGruber** [comment]
Could you try to update to the pre release 2.10.3

**Comment by Hoffenbar** [comment]
It works with the pre release!-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 01.01.23, 10:22 schrieb JackGruber ***@***.***>:

   
  Could you try to update to the pre release 2.10.3
