### ISSUE TITLE
Title variable

### ISSUE THREAD

**Issue by cestbonsuliu** [joplin/plugin-templates#73]
Hi, it seems that there is no built-in variable to get the title of the current note, if I want to customize the variable to get the title of the note, how do I do that?

**Comment by nishantwrp** [comment]
There is a variable for that `template_title`. 

Please refer to [this](https://github.com/joplin/plugin-templates#special-variables) section of the plugin documentation.

**Comment by nishantwrp** [comment]
@cestbonsuliu is this what you are looking for?
