### ISSUE TITLE
Suggestion: add template LICENSE file to scaffolded plugin

### ISSUE THREAD

**Issue by andypiper** [joplin/plugin-templates#76]
I noticed that a plugin that I want to contribute to, does not have a LICENSE file - so I opened an issue requesting that the status of the code be clarified.

It might be a good idea to add the creation of the LICENSE file to the template so that the author is prompted to add something. An alternative option would be to add a hint to the README file to suggest that the author clarifies license and contribution guidelines when they release or announce a new plugin.

**Comment by CalebJohn** [comment]
Hi @andypiper, I think maybe you meant to leave this comment under the [`generator-joplin`](https://github.com/laurent22/generator-joplin) project? It contains the yeoman template that is used for creating new plugins.

This is a repository for a Joplin plugin that adds note templating. Coincidentally, this plugin is missing a license, so your point is well received.

**Comment by andypiper** [comment]
you're completely right @CalebJohn - I will post this over there, and apologies for my confusion, appreciate being pointed in the right direction 👍🏻
