### ISSUE TITLE
Special variables doesn't work

### ISSUE THREAD

**Issue by Tiroelko** [joplin/plugin-templates#88]
May be I'm doing something wrong, but all other variables works just fine. And only special does nothing

**Comment by C3POH2SO4** [comment]
Have Same Problem: 
Example:
![2024-03-06_10h07_19](https://github.com/joplin/plugin-templates/assets/125547326/424924ff-1807-4ec7-b317-4f72f639c452)

Could there be a conflict with other Plugins? 

My Plugins right now (Desktop App Windows)
- Calendar 
- CodeMirror 6 snippets 
- CodeMirror Line Numbers
- CodeMirror Options
- CodePerfect
- Conflict Resolution
- Email Note
- Favorites
- Folding in Code Mirror Editor 
- Font Size Shortcut
- Hotfolder
- Inline tags
- Kanban
- Markdown Prettier
- Menu items, Shortcuts, Toolbar icons
- MultiMarkdown Table Tools
- Note list sidebar toggle buttons
- Persistent Editor Layout
- Plugin Bundle 
- Quick Links
- Rich Markdown
- Spoilers 
- Table Formatter Plugin 
- Tagging
- Templates 
- Text Colorize 
- Whitespacer 
- Backup

**Comment by nishantwrp** [comment]
Can you post an example.
