### ISSUE TITLE
Allow deltas for {{#custom_datetime}}FORMAT STRING{{/custom_datetime}}

### ISSUE THREAD

**Issue by mvilain** [joplin/plugin-templates#92]
allow specifying a time or date delta in the format string so I can specify a +1D or -1H etc. If this is already implemented, how can I specify it? I want to create a template with the current date as headers and +1 to +6 days in future. I can image someone else can use the +1H feature to create hourly entries

**Comment by nishantwrp** [comment]
Duplicate of #61.
